# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZYCycleScrollView_OC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZYCycleScrollView_OC
  pod 'SDWebImage'
  target 'ZYCycleScrollView_OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZYCycleScrollView_OCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
